services:
  Minimalist-Web-Notepad-Go:
    image: ghcr.io/gaoyaxuan/geoipgs:latest
    container_name: geoipgs
    restart: always
    network_mode: bridge
    volumes:
      #  数据位置
      - ./GeoLite2-City.mmdb:/app/GeoLite2-City.mmdb
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      # 默认映射到8080端口
      - "8080:8080"